export const styles = {
  page: {
    minHeight: "100vh",
    width: "100vw",
    background: "linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)",
    display: "flex",
    flexDirection: "column",
    padding: "20px 16px",
    overflowX: "hidden",
  },
  container: {
    width: "100%",
    maxWidth: "480px",
    margin: "0 auto",
  },
  header: {
    marginBottom: "24px",
    textAlign: "left",
  },
  headerTitle: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "4px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "700",
    color: "#0f172a",
    margin: 0,
    letterSpacing: "-0.5px",
  },
  titleBadge: {
    fontSize: "12px",
    background: "#e2e8f0",
    color: "#64748b",
    padding: "2px 8px",
    borderRadius: "12px",
    verticalAlign: "middle",
    marginLeft: "4px",
  },
  subtitle: {
    fontSize: "14px",
    color: "#64748b",
    margin: 0,
  },
  section: {
    marginBottom: "32px",
  },
  sectionLabel: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: "1px",
    marginBottom: "12px",
    display: "block",
  },
  cameraGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  actionCard: {
    background: "#ffffff",
    borderRadius: "12px",
    padding: "16px",
    display: "flex",
    alignItems: "center",
    gap: "16px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.02), 0 10px 20px -5px rgba(0,0,0,0.04)",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  iconContainer: {
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  cardContent: {
    flex: 1,
  },
  cardTitle: {
    margin: "0 0 2px 0",
    fontSize: "16px",
    fontWeight: "600",
    color: "#1e293b",
  },
  cardDescription: {
    margin: 0,
    fontSize: "12px",
    color: "#64748b",
  },
  utilGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "10px",
  },
  utilBtn: {
    border: "none",
    borderRadius: "12px",
    padding: "12px 8px",
    color: "#fff",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "8px",
    fontSize: "11px",
    fontWeight: "500",
    cursor: "pointer",
  },
  previewGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
  },
  emptyState: {
    gridColumn: "span 2",
    background: "#fff",
    border: "2px dashed #e2e8f0",
    borderRadius: "16px",
    padding: "40px 20px",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "12px",
    color: "#94a3b8",
    fontSize: "14px",
  },
  previewCard: {
    borderRadius: "12px",
    overflow: "hidden",
    background: "#fff",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
  },
  previewImageContainer: {
    position: "relative",
    aspectRatio: "1",
  },
  previewVideoContainer: {
    position: "relative",
    aspectRatio: "1",
    background: "#000",
    display: "flex",
    alignItems: "center",
  },
  previewImageContainerFull: {
    position: "relative",
    width: "100%",
    height: "200px",
  },
  imageFull: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  imageDetails: {
    padding: "12px",
    background: "#fff",
  },
  detailRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "12px",
    color: "#475569",
    marginBottom: "8px",
  },
  urlBox: {
    background: "#f8fafc",
    padding: "8px",
    borderRadius: "6px",
    border: "1px solid #e2e8f0",
  },
  urlLabel: {
    fontSize: "10px",
    color: "#64748b",
    fontWeight: "600",
    margin: "0 0 2px 0",
    textTransform: "uppercase",
  },
  urlLink: {
    fontSize: "10px",
    color: "#2563eb",
    textDecoration: "none",
    wordBreak: "break-all",
    display: "block",
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  video: {
    width: "100%",
  },
  previewBadge: {
    position: "absolute",
    bottom: "8px",
    left: "8px",
    background: "rgba(0,0,0,0.6)",
    color: "#fff",
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "10px",
    textTransform: "capitalize",
    backdropFilter: "blur(4px)",
  },
  dataCard: {
    padding: "12px",
    display: "flex",
    gap: "10px",
  },
  dataIcon: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    background: "#f1f5f9",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  dataContent: {
    minWidth: 0,
  },
  dataLabel: {
    fontSize: "10px",
    color: "#94a3b8",
    fontWeight: "600",
    textTransform: "uppercase",
  },
  dataValue: {
    fontSize: "14px",
    fontWeight: "700",
    color: "#1e293b",
    lineHeight: "1.2",
  },
  dataSub: {
    fontSize: "11px",
    color: "#64748b",
  },
  tokenText: {
    fontSize: "10px",
    color: "#475569",
    wordBreak: "break-all",
    marginTop: "4px",
    fontFamily: "monospace",
    background: "#f8fafc",
    padding: "8px",
    borderRadius: "6px",
    border: "1px solid #e2e8f0",
  },
  warningBox: {
    background: "#fff7ed",
    border: "1px solid #fed7aa",
    borderRadius: "12px",
    padding: "12px 16px",
    display: "flex",
    gap: "12px",
    marginBottom: "24px",
  },
  warningIcon: {
    fontSize: "20px",
  },
  warningText: {
    margin: "2px 0 0 0",
    fontSize: "12px",
    color: "#9a3412",
  },
  toast: {
    position: "fixed",
    top: "20px",
    left: "50%",
    transform: "translateX(-50%)",
    padding: "12px 20px",
    borderRadius: "100px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: "#fff",
    fontSize: "14px",
    fontWeight: "500",
    boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
    zIndex: 1000,
  },
  successToast: {
    background: "#059669",
  },
  errorToast: {
    background: "#dc2626",
  },
};
